# Generated by Django 5.2.7 on 2025-11-04 22:11

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('resumen', models.CharField(max_length=300)),
                ('imagen', models.ImageField(upload_to=projects.models.post_upload_to)),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
                ('codigo', models.IntegerField(unique=True)),
            ],
        ),
    ]
