# Generated by Django 5.2.7 on 2025-11-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_etiqueta_usuario_proyecto_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('toDo', 'Pendiente'), ('doing', 'En progreso'), ('done', 'Finalizado')], default='toDo', max_length=10),
        ),
    ]
